### ISSUE TITLE
No zooming / scrolling on mobile

### ISSUE THREAD

**Issue by LoggeL** [fionnfuchs/bubbleverse#2]
The game doesn't allow zooming or scrolling on mobile, which makes it impossible to reach certain menu elements. 

Aspect Ratio: 19.5:9

![photo_2019-11-09_16-30-25](https://user-images.githubusercontent.com/11969415/68531024-3e6d5700-030e-11ea-9b63-9b2dda25f99f.jpg)
![photo_2019-11-09_16-30-18](https://user-images.githubusercontent.com/11969415/68531025-3e6d5700-030e-11ea-8872-1c4800a605c5.jpg)

**Comment by fionnfuchs** [comment]
Currently the UI is fixed size. I will look into scrolling but for mobile there will maybe be a dedicated version in the future anyway.

**Comment by LoggeL** [comment]
Well mobile is already pretty playable if you ignore the fixed UI.

**Comment by jaskij** [comment]
It also looks bad on big screens. The screenshot below is from the browser window set to one half of a 34" 3440x1440 screen.

![image](https://user-images.githubusercontent.com/1429132/164774161-bf5f74de-c58c-40bf-86dc-9d94ec0f4c41.png)
